name: manga_easy_advanced_search
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  manga_easy_themes:
    git:
      url: https://github.com/lucascardo12/manga_easy_themes.git
      ref: 1.0.1
  manga_easy_sdk:
    git:
      url: https://github.com/lucascardo12/manga_easy_sdk.git
      ref: v.0.11.x
  coffee_cup:
    git:
      url: https://github.com/lucascardo12/manga_easy_coffee_cup.git
      ref: v0.11.x
  dio: ^4.0.6
  get_it: ^7.2.0
  manga_easy_routes:
    git:
      url: https://github.com/manga-easy/manga_easy_routes.git
      ref: v0.11.x
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

