name: manga_easy_advanced_search
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.1
  manga_easy_themes:
    git:
      url: https://github.com/lucascardo12/manga_easy_themes.git
      ref: 1.0.0

  coffee_cup:
    git:
      url: https://github.com/lucascardo12/manga_easy_coffee_cup
  cupertino_icons: ^1.0.2
  grouped_buttons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/
