name: manga_easy_advanced_search
description: A new Flutter package project.
version: 1.0.0
homepage:
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  manga_easy_themes:
    git:
      url: https://github.com/manga-easy/manga_easy_themes.git
      ref: 1.0.2
  manga_easy_sdk:
    git:
      url: https://github.com/manga-easy/manga_easy_sdk.git
      ref: v1.2.0
  coffee_cup:
    git:
      url: https://github.com/manga-easy/manga_easy_coffee_cup.git
      ref: v1.0.0
  get_it: ^7.2.0
  manga_easy_routes:
    git:
      url: https://github.com/manga-easy/manga_easy_routes.git
      ref: v0.0.2
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: v1.0.0
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.0.18
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
